# Generated by Django 6.1 on 2026-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='component_type',
            field=models.CharField(choices=[('none', 'Not a PC Component'), ('cpu', 'Processor (CPU)'), ('motherboard', 'Motherboard'), ('ram', 'Memory (RAM)'), ('storage', 'Storage (SSD/HDD)'), ('gpu', 'Graphics Card (GPU)'), ('psu', 'Power Supply (PSU)'), ('case', 'Casing'), ('cooler', 'CPU Cooler')], default='none', help_text='Maps category to PC Builder slot', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default='cpu', help_text='Icon class or SVG key', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deal_of_day',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='1 Year Brand Warranty', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='wattage',
            field=models.PositiveIntegerField(default=0, help_text='Power consumption in Watts for PC Builder calculation'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
