# Generated by Django 6.1 on 2026-08-20 19:42

from django.db import migrations
from decimal import Decimal

def add_smartphones(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Brand = apps.get_model('store', 'Brand')
    Product = apps.get_model('store', 'Product')

    # Get or create Smartphones category
    cat, _ = Category.objects.get_or_create(
        slug='smartphones',
        defaults={'name': 'Smartphones', 'component_type': 'none'}
    )

    # Get or create Brands
    apple, _ = Brand.objects.get_or_create(slug='apple', defaults={'name': 'Apple'})
    xiaomi, _ = Brand.objects.get_or_create(slug='xiaomi', defaults={'name': 'Xiaomi'})
    vivo, _ = Brand.objects.get_or_create(slug='vivo', defaults={'name': 'Vivo'})

    # Create Apple iPhone 17 Pro Max
    Product.objects.get_or_create(
        slug='apple-iphone-17-pro-max',
        defaults={
            'title': 'Apple iPhone 17 Pro Max',
            'brand': apple,
            'category': cat,
            'description': 'The ultimate iPhone with AI capabilities.',
            'base_price': Decimal('1199.00'),
            'is_active': True,
            'is_featured': True
        }
    )

    # Create Xiaomi 14 Ultra
    Product.objects.get_or_create(
        slug='xiaomi-14-ultra',
        defaults={
            'title': 'Xiaomi 14 Ultra 5G',
            'brand': xiaomi,
            'category': cat,
            'description': 'Leica optics, ultimate photography.',
            'base_price': Decimal('999.00'),
            'is_active': True,
            'is_featured': True
        }
    )

    # Create Vivo X100 Pro
    Product.objects.get_or_create(
        slug='vivo-x100-pro',
        defaults={
            'title': 'Vivo X100 Pro 5G',
            'brand': vivo,
            'category': cat,
            'description': 'Zeiss optics co-engineered imaging system.',
            'base_price': Decimal('899.00'),
            'is_active': True,
            'is_featured': True
        }
    )

def remove_smartphones(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Product.objects.filter(slug__in=['apple-iphone-17-pro-max', 'xiaomi-14-ultra', 'vivo-x100-pro']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner_question_review'),
    ]

    operations = [
        migrations.RunPython(add_smartphones, remove_smartphones),
    ]
